# Generated by Django 3.1.3 on 2020-11-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32),
        ),
    ]
