# Generated by Django 3.1.3 on 2020-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0002_auto_20201123_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('begintime', models.CharField(max_length=128)),
                ('endtime', models.CharField(max_length=128)),
                ('hours', models.CharField(max_length=20)),
            ],
        ),
    ]
