# Generated by Django 3.1.3 on 2020-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0003_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='day',
            field=models.CharField(max_length=128),
        ),
    ]
