# Generated by Django 3.1.3 on 2020-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0004_auto_20201123_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='begintime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='endtime',
            field=models.DateTimeField(),
        ),
    ]
