# Generated by Django 3.1.3 on 2020-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0005_auto_20201123_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='pid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
