# Generated by Django 3.1.3 on 2020-11-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0006_overtime_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='week',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
