# Generated by Django 3.1.3 on 2020-11-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0007_overtime_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='begintime',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='endtime',
            field=models.CharField(max_length=256),
        ),
    ]
