# Generated by Django 3.1.3 on 2020-11-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0008_auto_20201124_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtxt', models.CharField(max_length=256)),
                ('downdate', models.CharField(max_length=128)),
                ('pid', models.CharField(max_length=20)),
            ],
        ),
    ]
