# Generated by Django 3.1.3 on 2020-11-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0009_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
