# Generated by Django 3.1.3 on 2020-11-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0011_auto_20201127_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='color',
        ),
    ]
