# Generated by Django 3.1.3 on 2020-11-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0013_countdown_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='color',
        ),
    ]
