# Generated by Django 3.1.3 on 2020-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0015_countdown_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='color',
        ),
        migrations.AddField(
            model_name='countdown',
            name='color_downdate',
            field=models.CharField(default='#FF5722', max_length=20),
        ),
        migrations.AddField(
            model_name='countdown',
            name='color_downtxt',
            field=models.CharField(default='#1E9FFF', max_length=20),
        ),
    ]
