# Generated by Django 3.1.3 on 2020-11-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0016_auto_20201127_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='color_theme',
            field=models.CharField(default='#393D49', max_length=20),
        ),
    ]
