# Generated by Django 3.1.3 on 2020-12-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0018_auto_20201204_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_file',
            field=models.ImageField(default='phtots/default.jpg', upload_to='photos'),
        ),
    ]
