# Generated by Django 3.1.3 on 2021-01-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COH', '0026_overtime_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='year',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
    ]
